---
all:
  hosts:
    example-host-1:
        ansible_host: "10.0.0.11"
        mariadb_server_id: 1
        mariadb_incr_offset: 0
    example-host-2:
        ansible_host: "10.0.0.12"
        mariadb_server_id: 2
        mariadb_incr_offset: 1
  children:
    sshportal:
      hosts:
        example-host-1: {}
        example-host-2: {}
    db:
      hosts:
        example-host-1: {}
        example-host-2: {}
